//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Tests.TreesAndSections {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Tests.TreesAndSections.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;applications&gt;
        ///  &lt;add alias=&quot;content&quot; name=&quot;content&quot; icon=&quot;file&quot; sortOrder=&quot;0&quot; /&gt;
        ///  &lt;add alias=&quot;0b486ac9c0f1456996192c6ed1f03e57&quot; name=&quot;0b486ac9c0f1456996192c6ed1f03e57&quot; icon=&quot;icon.jpg&quot; sortOrder=&quot;1&quot; /&gt;
        ///  &lt;add alias=&quot;1ffbc301744c4e75ae3054d741954c7b&quot; name=&quot;1ffbc301744c4e75ae3054d741954c7b&quot; icon=&quot;icon.jpg&quot; sortOrder=&quot;2&quot; /&gt;
        ///  &lt;add alias=&quot;1838c3e1591f4008bbafe59a06a00a31&quot; name=&quot;1838c3e1591f4008bbafe59a06a00a31&quot; icon=&quot;icon.jpg&quot; sortOrder=&quot;3&quot; /&gt;
        ///  &lt;add alias=&quot;e5badae2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string applications {
            get {
                return ResourceManager.GetString("applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;trees&gt;
        ///  &lt;add initialize=&quot;false&quot; sortOrder=&quot;0&quot; alias=&quot;1838c3e1591f4008bbafe59a06a00a31&quot; application=&quot;1838c3e1591f4008bbafe59a06a00a31&quot; title=&quot;1838c3e1591f4008bbafe59a06a00a31&quot; iconClosed=&quot;icon.jpg&quot; iconOpen=&quot;icon.jpg&quot; type=&quot;nulltype&quot; /&gt;
        ///  &lt;add initialize=&quot;false&quot; sortOrder=&quot;0&quot; alias=&quot;e5badae2fc5e4cd7acb3700320e33b8b&quot; application=&quot;e5badae2fc5e4cd7acb3700320e33b8b&quot; title=&quot;e5badae2fc5e4cd7acb3700320e33b8b&quot; iconClosed=&quot;icon.jpg&quot; iconOpen=&quot;icon.jpg&quot; type=&quot;nulltype&quot; /&gt;
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string trees {
            get {
                return ResourceManager.GetString("trees", resourceCulture);
            }
        }
    }
}
