//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Web.UI.JavaScript {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Web.UI.JavaScript.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///    &apos;lib/jquery/jquery.min.js&apos;,
        ///    &apos;lib/angular/1.1.5/angular.min.js&apos;,
        ///    &apos;lib/underscore/underscore-min.js&apos;,
        ///
        ///    &apos;lib/moment/moment.min.js&apos;,
        ///
        ///    &apos;lib/animejs/anime.min.js&apos;,
        ///
        ///    &apos;lib/jquery-ui/jquery-ui.min.js&apos;,
        ///    &apos;lib/jquery-ui-touch-punch/jquery.ui.touch-punch.js&apos;,
        ///
        ///    &apos;lib/angular/1.1.5/angular-cookies.min.js&apos;,
        ///    &apos;lib/angular/1.1.5/angular-mobile.js&apos;,
        ///    &apos;lib/angular/1.1.5/angular-sanitize.min.js&apos;,
        ///
        ///    &apos;lib/angular/angular-ui-sortable.js&apos;,
        ///
        ///    &apos;lib/angular-dynamic-locale/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string JsInitialize {
            get {
                return ResourceManager.GetString("JsInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LazyLoad.js(&quot;##JsInitialize##&quot;, function () {
        ///    //we need to set the legacy UmbClientMgr path
        ///    UmbClientMgr.setUmbracoPath(&apos;&quot;##UmbracoPath##&quot;&apos;);
        ///
        ///    jQuery(document).ready(function () {
        ///
        ///        angular.bootstrap(document, [&apos;umbraco&apos;]);
        ///
        ///    });
        ///}); ähnelt.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die //TODO: This would be nicer as an angular module so it can be injected into stuff... that&apos;d be heaps nicer, but
        ///// how to do that when this is not a regular JS file, it is a server side JS file and RequireJS seems to only want
        ///// to force load JS files ?
        ///
        /////create the namespace (NOTE: This loads before any dependencies so we don&apos;t have a namespace mgr so we just create it manually)
        ///var Umbraco = {};
        ///Umbraco.Sys = {};
        /////define a global static object
        ///Umbraco.Sys.ServerVariables = ##Variables## ; ähnelt.
        /// </summary>
        internal static string ServerVariables {
            get {
                return ResourceManager.GetString("ServerVariables", resourceCulture);
            }
        }
    }
}
