//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Tests.UmbracoExamine {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Tests.UmbracoExamine.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;media&gt;
        ///	&lt;node id=&quot;1111&quot; version=&quot;902e13f7-5793-482a-9e06-cd94eebd1de0&quot; parentID=&quot;-1&quot; level=&quot;1&quot; writerID=&quot;0&quot; nodeType=&quot;1031&quot; template=&quot;0&quot; sortOrder=&quot;2&quot; createDate=&quot;2010-05-19T15:26:08&quot; updateDate=&quot;2010-05-19T15:26:09&quot; nodeName=&quot;Product Images&quot; urlName=&quot;productimages&quot; writerName=&quot;Administrator&quot; nodeTypeAlias=&quot;Folder&quot; path=&quot;-1,1111&quot;&gt;
        ///		&lt;data alias=&quot;contents&quot;&gt;&lt;/data&gt;
        ///		&lt;node id=&quot;2222&quot; version=&quot;902e13f7-5793-482a-9e06-cd94eebd1de0&quot; parentID=&quot;1111&quot; level=&quot;2&quot; writerID=&quot;0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE root[ 
        ///&lt;!ELEMENT CWS_Contact ANY&gt;
        ///&lt;!ATTLIST CWS_Contact id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EmailAFriend ANY&gt;
        ///&lt;!ATTLIST CWS_EmailAFriend id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EventItem ANY&gt;
        ///&lt;!ATTLIST CWS_EventItem id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Galleries ANY&gt;
        ///&lt;!ATTLIST CWS_Galleries id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Gallery ANY&gt;
        ///&lt;!ATTLIST CWS_Gallery id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Home ANY&gt;
        ///&lt;!ATTLIST CWS_Home id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_NewsEventsList ANY&gt;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string umbraco {
            get {
                return ResourceManager.GetString("umbraco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE root[ 
        ///&lt;!ELEMENT CWS_Contact ANY&gt;
        ///&lt;!ATTLIST CWS_Contact id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EmailAFriend ANY&gt;
        ///&lt;!ATTLIST CWS_EmailAFriend id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EventItem ANY&gt;
        ///&lt;!ATTLIST CWS_EventItem id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Galleries ANY&gt;
        ///&lt;!ATTLIST CWS_Galleries id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Gallery ANY&gt;
        ///&lt;!ATTLIST CWS_Gallery id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Home ANY&gt;
        ///&lt;!ATTLIST CWS_Home id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_NewsEventsList ANY&gt;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string umbraco_sort {
            get {
                return ResourceManager.GetString("umbraco_sort", resourceCulture);
            }
        }
    }
}
